[workspace]
resolver = "2"
members = [
    "bpa-server",
    "bpa",
    "bpa/fuzz",
    "bpv7",
    "bpv7/tools",
    "bpv7/fuzz",
    "cbor",
    "cbor/fuzz",
    "eid-patterns",
    "eid-patterns/fuzz",
    "file-cla",
    "localdisk-storage",
    "otel",
    "proto",
    "sqlite-storage",
    "tcpclv4",
    "tools",
]

[profile.release]
#lto = true
#codegen-units = 1

[workspace.package]
edition = "2024"

