[package]
name = "hardy-bpv7-tools"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "bundle"
path = "bundle.rs"

[dependencies]
hardy-bpv7 = { path = "..", features = ["std","serde","rfc9173"] }
hardy-cbor = { path = "../../cbor" }
clap = { version = "4.5.54", features = ["derive"] }
humantime = "2.3.0"
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
