[package]
name = "hardy-cbor"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
thiserror = "2.0.3"
half = { version = "2.4.1", features = ["std", "num-traits"] }
num-traits = "0.2.19"

[dev-dependencies]
hex-literal = "0.4.1"
