[package]
name = "hardy-proto"
version = "0.1.0"
edition.workspace = true

[lib]
path = "lib.rs"
crate-type = ["rlib"]

[features]
default = []
tracing = ["hardy-async/tracing"]

[dependencies]
hardy-async = { path = "../async" }
hardy-bpv7 = { path = "../bpv7" }
hardy-bpa = { path = "../bpa" }
tokio = { version = "1.49.0", features = ["rt-multi-thread", "time"] }
tokio-stream = "0.1.18"
tonic = "0.14.4"
tonic-prost = "0.14.4"
prost = "0.14.3"
prost-types = "0.14.3"
time = "0.3.47"
tracing = "0.1"

[build-dependencies]
tonic-prost-build = "0.14.4"
