[package]
name = "hardy-proto"
version = "0.1.0"
edition.workspace = true

[lib]
path = "lib.rs"
crate-type = ["rlib"]

[dependencies]
hardy-bpa = { path = "../bpa" }
tonic = "0.14.2"
tonic-prost = "0.14.2"
prost = "0.14.1"
prost-types = "0.14.1"
time = "0.3.44"

[build-dependencies]
tonic-prost-build = "0.14.2"
