[package]
name = "hardy-cbor-tools"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "cbor"
path = "cbor.rs"

[dependencies]
hardy-cbor = { path = ".." }
clap = { version = "4.5.54", features = ["derive"] }
anyhow = "1.0.100"
chumsky = "0.12.0"
hex = "0.4.3"
base64 = "0.22.1"
serde_json = "1.0"
